version: '3.7'



services:

  APIG4-compose:
    image: apig4:latest
    container_name: APIG4
    ports:
      - "5000:5000"
    volumes:
      - api:/var/lib/docker/volumes/vapi
    restart: unless-stopped

  BDD-compose:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: SQL
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${SA_PASSWORD}
    volumes:
      - mssql:/var/opt/mssql
    restart: unless-stopped

  mailhog-compose:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped



volumes:
  mssql:
  api:


networks:
  infra:
    driver: bridge
